name: publish

on: [push]

jobs:
  publish-barotrauma-server-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Barotrauma server Docker image
      run: |
        apt update && apt install -y libxml-parser-lite-perl && apt clean -y
        export BARO_VER=$(perl ./baro_ver.pl)
    - name: Build the Barotrauma server Docker image
      run: |
        docker build -f Dockerfile.prod . --tag ghcr.io/disinterpreter/barotrauma-server:latest --tag ghcr.io/disinterpreter/barotrauma-server:$BARO_VER
        docker push ghcr.io/disinterpreter/barotrauma-server:$BARO_VER
        docker push ghcr.io/disinterpreter/barotrauma-server:latest