name: publish

on: [push]

jobs:
  publish-barotrauma-server-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Barotrauma server Docker image
      run: |
        sudo apt update && sudo apt install -y libxml-parser-lite-perl && sudo apt clean -y
        export BARO_VER=$(perl ./barover.pl)
        docker build -f Dockerfile.prod -t ghcr.io/disinterpreter/barotrauma-server:latest -t ghcr.io/disinterpreter/barotrauma-server:$BARO_VER .
        docker push ghcr.io/disinterpreter/barotrauma-server:$BARO_VER
        docker push ghcr.io/disinterpreter/barotrauma-server:latest