name: publish

on: [push]

jobs:
  publish-barotrauma-server-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Barotrauma server Docker image
      run: |
        docker build -f Dockerfile.prod . --tag ghcr.io/disinterpreter/barotrauma-server:latest
        docker push ghcr.io/disinterpreter/barotrauma-server:latest